### ISSUE TITLE
installation fail

### ISSUE THREAD

**Issue by vanessamata** [udo-stenzel/biohazard#2]
Hi!

I've followed the instructions and installed the haskell platform and updated cabal, but when installing biohazard I get the following error:

[13 of 25] Compiling Bio.Bam.Rec      ( src/Bio/Bam/Rec.hs, dist/build/Bio/Bam/Rec.o )

src/Bio/Bam/Rec.hs:166:26: Not in scope: `pushEndOfInput'

src/Bio/Bam/Rec.hs:166:43: Not in scope: `runGetIncremental'

src/Bio/Bam/Rec.hs:166:64: Not in scope: `pushChunk'

src/Bio/Bam/Rec.hs:167:9:
    Not in scope: data constructor `Fail'
    Perhaps you meant `P.Fail' (imported from Data.Attoparsec.ByteString.Char8)

src/Bio/Bam/Rec.hs:168:9:
    Not in scope: data constructor `Partial'
    Perhaps you meant `P.Partial' (imported from Data.Attoparsec.ByteString.Char8)

src/Bio/Bam/Rec.hs:169:9:
    Not in scope: data constructor `Done'
    Perhaps you meant `P.Done' (imported from Data.Attoparsec.ByteString.Char8)
Failed to install biohazard-0.5.15.1
cabal: Error: some packages failed to install:
biohazard-0.5.15.1 failed during the building phase. The exception was:
ExitFailure 1

Any idea how to fix this?

Thanks

Vanessa

**Comment by udo-stenzel** [comment]
This is caused by an old version of binary being dragged in.  I bumped the dependency in master, that should fix it.  Please test!  (Thanks for the report.)

**Comment by vanessamata** [comment]
Thanks! That fixed that error! But I then got a new error eheh:

Loading package double-conversion-2.0.1.0 ... linking ... ghc: /home/vanessa/.cabal/lib/double-conversion-2.0.1.0/ghc-7.6.3/HSdouble-conversion-2.0.1.0.o: unknown symbol `_ZNK17double_conversion23StringToDoubleConverter12StringToIeeeIPKcEEdT_ibPi'
ghc: unable to load package `double-conversion-2.0.1.0'
Failed to install biohazard-0.5.15.1
cabal: Error: some packages failed to install:
biohazard-0.5.15.1 failed during the building phase. The exception was:
ExitFailure 1

any idea?

thanks again!

**Comment by udo-stenzel** [comment]
Your installation of double-conversion is broken.  That shouldn't happen by itself.  Did you try 
'cabal install ... --force-reinstalls'?  'ghc-pkg check' might tell you what needs to be reinstalled now, and if that doesn't help, see http://www.vex.net/~trebla/haskell/sicp.xhtml#remove to get out of the mess.  The way it is, your particular failure cannot be reproduced anywhere, because it's tied to your particular installation.

**Comment by vanessamata** [comment]
I tried what you suggested, but that didn't help. I've tried on several computers and I always got the same error, so I don't think this is just my problem. I was able to get help from a friend, and apparently a lot of dependencies were missing, he was able to fix it step by step until we were able to run the program, but the installation was still not fully completed. Right now just following your installation procedure we were not able to install biohazard in any computer :(

**Comment by udo-stenzel** [comment]
That doesn't make sense--cabal takes care of dependencies, unless you mess your installation up by doing an 'install -force-reinstalls'.  Anyway, I'd like you to do the following, literally:

> rm -r ~/.cabal ~/.ghc
> cabal update
> git clone https://github.com/udo-stenzel/biohazard
> cabal install biohazard/

If that fails, please tell me the exact error message.  If that error messsage says "...because it depends on X, which failed to install", scroll up to the message regarding X, that's the actually important one.   Also tell me the version of GHC (output of `ghc --version`) and Cabal (output of `cabal --version`) and the Haskell Platform, if you installed it (`dpkg -l haskell-platform` might work).

**Comment by udo-stenzel** [comment]
Progress:  I can reproduce the nonsense on a pristine virtual machine.  Apparently, double-conversion drags in a dependency on a C++ compiler(!), and there is some miscommunication between GHC and G++.  I'll get rid of that particular package... somehow.

**Comment by udo-stenzel** [comment]
Should be fixed.  (What an awful interaction between Haskell, Template Haskell, and C++.)
Can you install now?
